# Assignment 1 - Probability, Linear Algebra, Programming, and Git

## *Maobin Guo*
Netid: mg471

Instructions for all assignments can be found [here](https://github.com/kylebradbury/ids705/blob/master/assignments/_Assignment%20Instructions.ipynb), which is also linked to from the [course syllabus](https://kylebradbury.github.io/ids705/index.html).

#  Learning Objectives
The purpose of this assignment is to provide a refresher on fundamental concepts that we will use throughout this course, and provide an opportunity to develop skills in any of the related skills that may be unfamiliar to you. Through the course of completing this assignment, you will... 
- Refresh you knowledge of probability theory including properties of random variables, probability density functions, cumulative distribution functions, estimating probabilities through counting, and key statistics such as mean and variance.
- Revisit common linear algebra and matrix operations and concepts such as matrix multiplication, inner and outer products, inverses, the Hadamard (element-wise) product, eigenvalues and eigenvectors, orthogonality, and symmetry.
- Practice numerical programming, core to machine learning, by loading and filtering data, plotting data, vectorizing operations, profiling code speed, and debugging and optimizing performance. You will also practice computing probabilities based on simulation.
- Develop or refresh your knowledge of Git version control, which will be a core tool used in the final project of this course
- Apply your skills altogether through an exploratory data analysis to practice data cleaning, data manipulation, intepretation, and communication 

We will build on these concepts throughout the course, so use this assignment as a catalyst to deepen your knowledge and seek help with anything that is unfamiliar.

# Probability and Statistics Theory

*Note: for all assignments, write out all equations and math using markdown and [LaTeX](https://tobi.oetiker.ch/lshort/lshort.pdf). For this assignment show ALL math work*

## 1
**[3 points]**  
Let $f(x) = \begin{cases}
                0           & x < 0  \\
                \alpha x^2  & 0 \leq x \leq 2 \\
                0           & 2 < x
            \end{cases}$
            
For what value of $\alpha$ is $f(x)$ a valid probability density function?

**ANSWER** ：

**For**
$\int_{-\infty}^{\infty}f(x)dx = \int_{0}^{2}ax^2 = \frac{8}{3}a = 1$

**Hence** 
a = $\frac{3}{8}$



## 2
**[3 points]** What is the cumulative distribution function (CDF) that corresponds to the following probability distribution function? Please state the value of the CDF for all possible values of $x$.

$f(x) = \begin{cases}
    \frac{1}{3} & 0 < x < 3 \\
    0           & \text{otherwise}
    \end{cases}$

**ANSWER**

$\int\frac{1}{3}dx = \frac{x}{3} + c$ <br>

For $\int_{0}^{3}\frac{1}{3}dx = 1$ , Thus c = 0  

$F(x) = \begin{cases}
        0 & x < 0 \\
        \frac{x}{3} & 0 \leq x \leq 3 \\
        1 & 3 <  x 
        \end{cases}$




## 3
**[6 points]** For the probability distribution function for the random variable $X$,

$f(x) = \begin{cases}
    \frac{1}{3} & 0 < x < 3 \\
    0           & \text{otherwise}
    \end{cases}$
    
what is the (a) expected value and (b) variance of $X$. *Show all work*.

**ANSWER**

**(a) expected value**
$E(x) = \int_{-\infty}^{\infty}xf(x)dx$ <br>

For this distribution : <br>

$E(x) = \int_{0}^{3}\frac{x}{3}dx = \left [ {\frac{x^2}{6}}\right ]_{0}^{3} = \frac{3}{2} $

expected value is  $\frac{3}{2}$

**(b) variance**

$V(x) = \int_{-\infty}^{\infty}(x-E(x))^2f(x)dx$ <br>

For this distribution : <br>

$
\begin{equation}
\begin{split}
V(x) & =  \int_{0}^{3}\frac{1}{3}(x - E(x))^2 dx \\
     & =  \int_{0}^{3}\frac{1}{3}(x - 1.5)^2 dx \\
     & = \frac{1}{3} \left [ {\frac{1}{3} (x - 1.5)^3}  \right ]_{0}^{3} \\ 
     & = 0.75
\end{split}
\end{equation}
$


## 4
**[6 points]** Consider the following table of data that provides the values of a discrete data vector $\mathbf{x}$ of samples from the random variable $X$, where each entry in $\mathbf{x}$ is given as $x_i$.

*Table 1. Dataset N=5 observations*

|        | $x_0$ | $x_1$ | $x_2$ | $x_3$ | $x_4$ |
|------  |-------|-------|-------|-------|-------|
|$\textbf{x}$| 2     | 3     | 10    | -1    | -1    |

What is the (a) mean, (b) variance, and the  of the data? 

*Show all work. Your answer should include the definition of mean, median, and variance in the context of discrete data.*

**ANSWER**

##### 1. mean

$\mu = \frac{(x_0 + x_1 + x_2 + x_3 + x_4)}{N}  = \frac{(2+3+10-1-1)}{5} =\frac{13}{5} = 2.6$

##### 2. median
Sorted Data:  -1, -1, 2, 3, 10 <br>
median = 2 ; because it is in the middel of above array


##### 3. variance

$ 
\begin{equation}
\begin{split}
variance  & = \sum (x_i - \mu)^2 p(x_i) \\
          & = \frac{1}{5}((2 - \frac{13}{5})^2 + (3 - \frac{13}{5})^2 + (10 - \frac{13}{5})^2 + (-1 - \frac{13}{5})^2) + (-1 - \frac{13}{5})^2) \\
          & = \frac{406}{25} =  16.24
\end{split}
\end{equation}
$


## 5
**[8 points]** Review of counting from probability theory. 

(a) How many different 7-place license plates are possible if the first 3 places only contain letters and the last 4 only contain numbers?

(b) How many different batting orders are possible for a baseball team with 9 players?

(c) How many batting orders of 5 players are possible for a team with 9 players total?

(d) Let's assume this class has 26 students and we want to form project teams. How many unique teams of 3 are possible?

*Hint: For each problem, determine if order matters, and if it should be calculated with or without replacement.*

**ANSWER**

##### (a)
It's a 7-place replaceable permutation   <br>
$26^3 \times  10^4 = 175760000$

##### (b)
It's a full permutation of 9 <br>
$9! = 362880$

##### (c)
There are 2 steps:
1. Select 5 player from 9 player, there are ${9 \choose 5}$ possible methods
2. Order the 5 selected player, it's a full permutation so there are $5!$ possible methods

Total method: <br>

${9 \choose 5} \times 5! = \frac{9!}{(9-5)! \times 5!} \times 5! = 9 \times 8 \times 7 \times 6 \times 5 = 15120 $


##### (d) 
Choose 3 from 26 <br>

${{26}\choose{3}} = \frac{26!}{(26-3)!3!}= 2600$ 

# Linear Algebra

## 6
**[7 points]** **Matrix manipulations and multiplication**. Machine learning involves working with many matrices, so this exercise will provide you with the opportunity to practice those skills.

Let
$\mathbf{A} =  \begin{bmatrix}
1 & 2 & 3 \\
2 & 4 & 5 \\
3 & 5 & 6 
\end{bmatrix}$, $\mathbf{b} =  \begin{bmatrix}
-1  \\
3  \\
8  
\end{bmatrix}$, $\mathbf{c} =  \begin{bmatrix}
4  \\
-3  \\
6  
\end{bmatrix}$, and $\mathbf{I} =  \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 
\end{bmatrix}$

Compute the following or indicate that it cannot be computed:

1. $\mathbf{A}\mathbf{A}$
2. $\mathbf{A}\mathbf{A}^T$
3. $\mathbf{A}\mathbf{b}$
4. $\mathbf{A}\mathbf{b}^T$
5. $\mathbf{b}\mathbf{A}$
6. $\mathbf{b}^T\mathbf{A}$
7. $\mathbf{b}\mathbf{b}$
8. $\mathbf{b}^T\mathbf{b}$
9. $\mathbf{b}\mathbf{b}^T$
10. $\mathbf{b} + \mathbf{c}^T$
11. $\mathbf{b}^T\mathbf{b}^T$
12. $\mathbf{A}^{-1}\mathbf{b}$
13. $\mathbf{A}\circ\mathbf{A}$
14. $\mathbf{b}\circ\mathbf{c}$

*Note: The element-wise (or Hadamard) product is the product of each element in one matrix with the corresponding element in another matrix, and is represented by the symbol "$\circ$".*

**ANSWER**

In [1]:
import numpy as np
A = np.matrix([(1,2,3),
              (2,4,5),
              (3,5,6)])
b = np.array([-1,3,8])
c = np.array([4,-3,6])
I = np.matrix([(1,0,0),
              (0,1,0),
              (0,0,1)])

##### 1.  $\mathbf{A}\mathbf{A}$

In [7]:
print('AA = \n {}'.format(np.matmul(A,A)))

AA = 
 [[14 25 31]
 [25 45 56]
 [31 56 70]]


##### 2. $\mathbf{A}\mathbf{A}^T$

In [12]:
print('A(A^T) = \n {}'.format(np.matmul(A,A.T)))

A(A^T) = 
 [[14 25 31]
 [25 45 56]
 [31 56 70]]


##### 3. $\mathbf{A}\mathbf{b}$

In [13]:
print('Ab = \n {}'.format(np.matmul(A,b)))

Ab = 
 [[29 50 60]]


##### 4. $\mathbf{A}\mathbf{b}^T$

The operation will fail because $A$ is a $3 \times 3$ matrix while $b^T$ is $1 \times 3$ matrix

##### 5. $\mathbf{b}\mathbf{A}$

The operation will fail because $b^T$ is $3 \times 1$ matrix while $A$ is a $3 \times 3$ matrix while 

##### 6. $\mathbf{b}^T\mathbf{A}$

In [23]:
print('b^TA = \n {}'.format(np.matmul(b.T,A)))

b^TA = 
 [[29 50 60]]


##### 7. $\mathbf{b}\mathbf{b}$

The operation will fail because $3 \times 1$ matrix can not multiply another $3 \times 1$ matrix

##### 8. $\mathbf{b}^T\mathbf{b}$

In [17]:
print('b^Tb = \n {}'.format(np.matmul(b.T,b)))

b^Tb = 
 74


##### 9. $\mathbf{b}\mathbf{b}^T$

In [22]:
print('bb^T = \n {}'.format(np.matmul(np.matrix([(-1),(3),(8)]).T,np.matrix([(-1),(3),(8)]))))

bb^T = 
 [[ 1 -3 -8]
 [-3  9 24]
 [-8 24 64]]


##### 10. $\mathbf{b} + \mathbf{c}^T$

The operation will fail because $b$ is a $3 \times 1$ matrix while $c^T$ is $1 \times 3$ matrix

##### 11. $\mathbf{b}^T\mathbf{b}^T$

The operation will fail because $b$ is a $1 \times 3$ matrix while $b^T$ is $1 \times 3$ matrix

##### 12. $\mathbf{A}^{-1}\mathbf{b}$

In [25]:
print('A^-1b = \n {}'.format(np.matmul(np.linalg.inv(A), b)))

A^-1b = 
 [[ 6.  4. -5.]]


##### 13. $\mathbf{A}\circ\mathbf{A}$

In [26]:
print('A.A = \n {}'.format(np.multiply(A, A)))

A.A = 
 [[ 1  4  9]
 [ 4 16 25]
 [ 9 25 36]]


##### 14. $\mathbf{b}\circ\mathbf{c}$

In [27]:
print('b.c = \n {}'.format(np.multiply(b, c)))

b.c = 
 [-4 -9 48]


## 7
**[8 points]** **Eigenvectors and eigenvalues**. Eigenvectors and eigenvalues are useful for some machine learning algorithms, but the concepts take time to solidly grasp. For an intuitive review of these concepts, explore this [interactive website at Setosa.io](http://setosa.io/ev/eigenvectors-and-eigenvalues/). Also, the series of linear algebra videos by Grant Sanderson of 3Brown1Blue are excellent and can be viewed on youtube [here](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab).

1. Calculate the eigenvalues and corresponding eigenvectors of matrix $\mathbf{A}$ above, from the last question.
2. Choose one of the eigenvector/eigenvalue pairs, $\mathbf{v}$ and $\lambda$, and show that $\mathbf{A} \mathbf{v} = \lambda \mathbf{v}$. Also show that this relationship extends to higher orders: $\mathbf{A} \mathbf{A} \mathbf{v} = \lambda^2 \mathbf{v}$
3. Show that the eigenvectors are orthogonal to one another (e.g. their inner product is zero). This is true for real, symmetric matrices.

**ANSWER**

##### 1.  Eigenvalues and corresponding eigenvectors

$det[\mathbf{A} - \lambda\mathbf{I}] = 0 \\
\Rightarrow  (1-\lambda)  det \begin{bmatrix}
4-\lambda & 5 \\
5 & 6-\lambda \end{bmatrix}
- 2 det \begin{bmatrix}
2 & 5 \\
3 & 6-\lambda \end{bmatrix}
+ 3 det \begin{bmatrix}
2 & 4-\lambda \\
3 & 5 \end{bmatrix} = 0 \\
\Rightarrow  (1-\lambda)((4-\lambda)(6-\lambda)-25) - 2(2(6-\lambda)-15) + 3(10-3(4-\lambda) = 0 \\
\Rightarrow  -\lambda^3 + 11\lambda^2 + 4\lambda -1 = 0 $

$\lambda_0 = 11.3448 \\
\lambda_1 = -0.5157 \\
\lambda_2 = 0.1709$

$v_0 = \begin{bmatrix}
-0.328 \\
-0.591 \\
-0.737
\end{bmatrix}$

$v_1 = \begin{bmatrix}
-0.737 \\
-0.328 \\
0.591
\end{bmatrix}$

$v_2 = \begin{bmatrix}
0.591 \\
-0.737 \\
0.328
\end{bmatrix}$

In [39]:
import numpy as np
from numpy import linalg 

np.set_printoptions(precision=4)

eival, eivec = linalg.eig(A)

rank = linalg.matrix_rank(A)

print("There are {} pairs of eigenvalues and eigenvector".format(rank))

for i in range(rank):
    print("{}.)".format(i))
    print(eivec[:,i])
    print("{:.4f}".format(eival[i]))

There are 3 pairs of eigenvalues and eigenvector
0.)
[[-0.328]
 [-0.591]
 [-0.737]]
11.3448
1.)
[[-0.737]
 [-0.328]
 [ 0.591]]
-0.5157
2.)
[[ 0.591]
 [-0.737]
 [ 0.328]]
0.1709


##### 2. Choose one of the eigenvector/eigenvalue pairs, $\mathbf{v}$ and $\lambda$, and show that $\mathbf{A} \mathbf{v} = \lambda \mathbf{v}$. Also show that this relationship extends to higher orders: $\mathbf{A} \mathbf{A} \mathbf{v} = \lambda^2 \mathbf{v}$

$\lambda_0 = 11.3448$

$\mathbf{v_0} = \begin{bmatrix}
-0.328 \\
-0.591 \\
-0.737 \end{bmatrix}$

$\mathbf{A} \mathbf{v_0} = \begin{bmatrix}
1 & 2 & 3 \\
2 & 4 & 5 \\
3 & 5 & 6 \end{bmatrix}
\begin{bmatrix}
-0.328 \\
-0.591 \\
-0.737 \end{bmatrix}
= \begin{bmatrix}
-3.720 \\
-6.705 \\
-8.361 \end{bmatrix}$

$\lambda_0 \mathbf{v_0} = 11.3448 \begin{bmatrix}
-0.328 \\
-0.591 \\
-0.737 \end{bmatrix}
= \begin{bmatrix}
-3.720 \\
-6.705 \\
-8.361 \end{bmatrix}$

$\mathbf{A} \mathbf{A} \mathbf{v_0} = \begin{bmatrix}
1 & 2 & 3 \\
2 & 4 & 5 \\
3 & 5 & 6 \end{bmatrix}
\begin{bmatrix}
1 & 2 & 3 \\
2 & 4 & 5 \\
3 & 5 & 6 \end{bmatrix}
\begin{bmatrix}
-0.328 \\
-0.591 \\
-0.737 \end{bmatrix}
= \begin{bmatrix}
-42.213 \\
-76.066 \\
-94.852 \end{bmatrix}$

${\lambda_0}^2 \mathbf{v_0} = {11.3448}^2 \begin{bmatrix}
-0.328 \\
-0.591 \\
-0.737 \end{bmatrix}
= \begin{bmatrix}
-42.213 \\
-76.066 \\
-94.852 \end{bmatrix}$

$\mathbf{A} \mathbf{v}$

In [45]:
print(np.dot(A, eivec[:, 0]))

[[-3.7209]
 [-6.7049]
 [-8.3609]]


$\lambda \mathbf{v}$

In [46]:
print("A*v:")
print(eivec[:, 0]*eival[0])

A*v:
[[-3.7209]
 [-6.7049]
 [-8.3609]]


So : $\mathbf{A} \mathbf{v} = \lambda \mathbf{v}$

$\mathbf{A} \mathbf{A} \mathbf{v}$

In [48]:
print(np.dot(np.dot(A, A), eivec[:, 0]))

[[-42.2133]
 [-76.0657]
 [-94.8524]]


$\lambda^2 \mathbf{v}$

In [55]:
print(eivec[:, 0]*eival[0]*eival[0])

[[-42.2133]
 [-76.0657]
 [-94.8524]]


So: $\mathbf{A} \mathbf{A} \mathbf{v} = \lambda^2 \mathbf{v}$

##### 3. Show that the eigenvectors are orthogonal to one another (e.g. their inner product is zero). This is true for real, symmetric matrices.


$\mathbf{v_0}\mathbf{v_1} = \begin{bmatrix} -0.328\ -0.591\ -0.737 \end{bmatrix}
\begin{bmatrix}
-0.737 \\
-0.328 \\
0.591
\end{bmatrix} = 0$

$\mathbf{v_1}\mathbf{v_2} = \begin{bmatrix} -0.328\ -0.591\ -0.737 \end{bmatrix}
\begin{bmatrix}
0.591 \\
-0.737 \\
0.328
\end{bmatrix} = 0$

$\mathbf{v_2}\mathbf{v_0} = \begin{bmatrix} -0.737\ -0.328\ 0.591 \end{bmatrix}
\begin{bmatrix}
0.591 \\
-0.737 \\
0.328
\end{bmatrix} = 0$

In [68]:
print('v0 * v1 is zero ', np.isclose(0, np.dot(eivec[:, 0].T, eivec[:, 1]))[0,0] )
print('v1 * v2 is zero ', np.isclose(0, np.dot(eivec[:, 1].T, eivec[:, 2]))[0,0] )
print('v2 * v0 is zero ', np.isclose(0, np.dot(eivec[:, 2].T, eivec[:, 0]))[0,0] )

v0 * v1 is zero  True
v1 * v2 is zero  True
v2 * v0 is zero  True


Since all inner product is 0, so the eigenvectors are orthogonal to one another.

# Numerical Programming

## 8
**[10 points]** Loading data and gathering insights from a real dataset

**Data**. The data for this problem can be found in the `data` subfolder in the `assignments` folder on [github](https://github.com/kylebradbury/ids705). The filename is `egrid2016.xlsx`. This dataset is the Environmental Protection Agency's (EPA) [Emissions & Generation Resource Integrated Database (eGRID)](https://www.epa.gov/energy/emissions-generation-resource-integrated-database-egrid) containing information about all power plants in the United States, the amount of generation they produce, what fuel they use, the location of the plant, and many more quantities. We'll be using a subset of those data.

The fields we'll be using include:					
    
|field    |description|
|:-----   |:-----|
|SEQPLT16 |eGRID2016 Plant file sequence number (the index)| 
|PSTATABB |Plant state abbreviation|
|PNAME    |Plant name |
|LAT      |Plant latitude |
|LON      |Plant longitude|
|PLPRMFL  |Plant primary fuel |
|CAPFAC   |Plant capacity factor |
|NAMEPCAP |Plant nameplate capacity (Megawatts MW)|
|PLNGENAN |Plant annual net generation (Megawatt-hours MWh)|
|PLCO2EQA |Plant annual CO2 equivalent emissions (tons)|

For more details on the data, you can refer to the [eGrid technical documents](https://www.epa.gov/sites/production/files/2018-02/documents/egrid2016_technicalsupportdocument_0.pdf). For example, you may want to review page 45 and the section "Plant Primary Fuel (PLPRMFL)", which gives the full names of the fuel types including WND for wind, NG for natural gas, BIT for Bituminous coal, etc.

There also are a couple of "gotchas" to watch out for with this dataset:
- The headers are on the second row and you'll want to ignore the first row (they're more detailed descriptions of the headers).
- NaN values represent blanks in the data. These will appear regularly in real-world data, so getting experience working with it will be important.

**Your objective**. For this dataset, your goal is answer the following questions about electricity generation in the United States:

**(a)** Which plant has generated the most energy (measured in MWh)?

**(b)** What is the name of the northern-most power plant in the United States?

**(c)** What is the state where the northern-most power plant in the United States is located?

**(d)** Plot a bar plot showing the amount of energy produced by each fuel for the plant. 

**(e)** From the plot in (d), which fuel for generation produces the most energy (MWh) in the United States?

**ANSWER**

In [4]:
import os
import pandas as pd

df = pd.read_excel('./data/egrid2016.xlsx', skiprows=[0], engine='openpyxl')
df.head()

SEQPLT16 PSTATABB                             PNAME        LAT         LON  \
0         1       AK         7-Mile Ridge Wind Project  63.210689 -143.247156   
1         2       AK  Agrium Kenai Nitrogen Operations  60.673200 -151.378400   
2         3       AK                          Alakanuk  62.683300 -164.654400   
3         4       AK               Allison Creek Hydro  61.084444 -146.353333   
4         5       AK                            Ambler  67.087980 -157.856719   

  PLPRMFL   CAPFAC  NAMEPCAP  PLNGENAN  PLCO2EQA  
0     WND      NaN       1.8       NaN       NaN  
1      NG      NaN      21.6       NaN       NaN  
2     DFO  0.05326       2.6  1213.001  1049.863  
3     WAT  0.01547       6.5   881.000     0.000  
4     DFO  0.13657       1.1  1315.999  1087.881

**(a)** Which plant has generated the most energy (measured in MWh)?

In [14]:
df[df["PLNGENAN"] == df["PLNGENAN"].max()][["PSTATABB", "PNAME"]]

PSTATABB       PNAME
390       AZ  Palo Verde

**Palo Verde**  plant generated the most energy 

**(b)** What is the name of the northern-most power plant in the United States?

In [15]:
df[df["LAT"] == df["LAT"].max()][["PSTATABB", "PNAME"]]

PSTATABB   PNAME
11       AK  Barrow

**Barrow** is the northern-most power plant

**(c)** What is the state where the northern-most power plant in the United States is located?

In [ ]:
df[df["LAT"] == df["LAT"].max()][["PSTATABB", "PNAME"]]

The northern-most power plant is in **AK (Alaska)**

**(d)** Plot a bar plot showing the amount of energy produced by each fuel for the plant. 

In [37]:
import seaborn as sns
import matplotlib.pyplot as plt

df_fule = df[['PLPRMFL','PLNGENAN']]
#df_fule.dropna()
df_fule = df_fule.groupby('PLPRMFL').sum()

plt.figure(figsize=(20,10))
sns.barplot(x='PLPRMFL', y='PLNGENAN', data=df_fule, ci=None)
plt.xlabel('Fuel')
plt.ylabel('Annual net generation (MWh)')
plt.title('The amount of energy produced by each fuel for the plantt')
plt.show()

ValueError: Could not interpret input 'PLPRMFL'

<Figure size 1440x720 with 0 Axes>

PLPRMFL     PLNGENAN
0        WND          NaN
1         NG          NaN
2        DFO     1213.001
3        WAT      881.000
4        DFO     1315.999
...      ...          ...
9704      NG     6893.790
9705     SUB   710524.000
9706     SUB   734354.000
9707     SUB   821699.000
9708     SUB  2056358.000

[9709 rows x 2 columns]

**(e)** From the plot in (d), which fuel for generation produces the most energy (MWh) in the United States?

In [33]:
df[['PLPRMFL','PLNGENAN']].groupby('PLPRMFL') \
.sum().sort_values('PLNGENAN', ascending=False).iloc[0]

PLNGENAN    1.314956e+09
Name: NG, dtype: float64

## 9
**[8 points]** Speed comparison between vectorized and non-vectorized code. Begin by creating an array of 10 million random numbers using the numpy random.randn module. Compute the sum of the squares first in a for loop, then using Numpy's `dot` module. Time how long it takes to compute each and report the results and report the output. How many times faster is the vectorized code than the for loop approach?

*Note: all code should be well commented, properly formatted, and your answers should be output using the `print()` function as follows (where the # represents your answers, to a reasonable precision):

`Time [sec] (non-vectorized): ######`

`Time [sec] (vectorized):     ######`

`The vectorized code is ##### times faster than the vectorized code`

**ANSWER**

## 10
**[10 points]** One popular Agile development framework is Scrum (a paradigm recommended for data science projects). It emphasizes the continual evolution of code for projects, becoming progressively better, but starting with a quickly developed minimum viable product. This often means that code written early on is not optimized, and that's a good thing - it's best to get it to work first before optimizing. Imagine that you wrote the following code during a sprint towards getting an end-to-end system working. Vectorize the following code and show the difference in speed between the current implementation and a vectorized version.

The function below computes the function $f(x,y) = x^2 - 2 y^2$ and determines whether this quantity is above or below a given threshold, `thresh=0`. This is done for $x,y \in \{-4,4\}$, over a 2,000-by-2,000 grid covering that domain.

(a) Vectorize this code and demonstrate (as in the last exercise) the speed increase through vectorization and (b) plot the resulting data - both the function $f(x,y)$ and the thresholded output - using [`imshow`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html?highlight=matplotlib%20pyplot%20imshow#matplotlib.pyplot.imshow) from `matplotlib`.

*Hint: look at the `numpy` [`meshgrid`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.meshgrid.html) documentation*

**ANSWER**

In [1]:
import numpy as np
import time
import matplotlib.pyplot as plt

nvalues = 2000
xvalues = np.linspace(-4,4,nvalues)
yvalues = np.linspace(-4,4,nvalues)
thresh  = 0

# Nonvectorized implementation
t0 = time.time()
f = np.zeros((nvalues,nvalues))
f_thresholded = np.zeros((nvalues,nvalues))
for ix, x in enumerate(xvalues):
    for iy, y in enumerate(yvalues):
        f[ix,iy]             = x**2 - 2 * y**2
        f_thresholded[ix,iy] = f[ix,iy] > thresh
t1 = time.time()
time_nonvectorized = t1 - t0

# Vectorized implementation

# Vectorization speed performance results

# Plot the function f(x,y)


## 11
**[10 points]** This exercise will walk through some basic numerical programming exercises.
1. Synthesize $n=10^4$ normally distributed data points with mean $\mu=2$ and a standard deviation of $\sigma=1$. Call these observations from a random variable $X$, and call the vector of observations that you generate, $\textbf{x}$.
2. Calculate the mean and standard deviation of $\textbf{x}$ to validate (1) and provide the result to a precision of four significant figures.
3. Plot a histogram of the data in $\textbf{x}$ with 30 bins
4. What is the 90th percentile of $\textbf{x}$? The 90th percentile is the value below which 90% of observations can be found.
5. What is the 99th percentile of $\textbf{x}$?
6. Now synthesize $n=10^4$ normally distributed data points with mean $\mu=0$ and a standard deviation of $\sigma=3$. Call these observations from a random variable $Y$, and call the vector of observations that you generate, $\textbf{y}$.
7. Create a new figure and plot the histogram of the data in $\textbf{y}$ on the same axes with the histogram of $\textbf{x}$, so that both histograms can be seen and compared.
8. Using the observations from $\textbf{x}$ and $\textbf{y}$, estimate $E[XY]$

**ANSWER**

# Version Control via Git

## 12
**[1 point]** You will need to use Git to submit assignments and in the course projects and is generally a version control and collaboration tool. You can even use some Git repositories (e.g. Github) as hosts for website, such as with the [course website](https://kylebradbury.github.io/ids705/index.html). 

Complete the [Atlassian Git tutorial](https://www.atlassian.com/git/tutorials/what-is-version-control), specifically the following listed sections. Try each concept that's presented. For this tutorial, instead of using BitBucket as your remote repository host, you may use your preferred platform such as [Github](https://github.com/) or [Duke's Gitlab](https://gitlab.oit.duke.edu/users/sign_in).
1. [What is version control](https://www.atlassian.com/git/tutorials/what-is-version-control)
2. [What is Git](https://www.atlassian.com/git/tutorials/what-is-git)
3. [Install Git](https://www.atlassian.com/git/tutorials/install-git)
4. [Setting up a repository](https://www.atlassian.com/git/tutorials/install-git)
5. [Saving changes](https://www.atlassian.com/git/tutorials/saving-changes)
6. [Inspecting a repository](https://www.atlassian.com/git/tutorials/inspecting-a-repository)
7. [Undoing changes](https://www.atlassian.com/git/tutorials/undoing-changes)
8. [Rewriting history](https://www.atlassian.com/git/tutorials/rewriting-history)
9. [Syncing](https://www.atlassian.com/git/tutorials/syncing)
10. [Making a pull request](https://www.atlassian.com/git/tutorials/making-a-pull-request)
11. [Using branches](https://www.atlassian.com/git/tutorials/using-branches)
12. [Comparing workflows](https://www.atlassian.com/git/tutorials/comparing-workflows)

I also have created two videos on the topic to help you understand some of these concepts: [Git basics](https://www.youtube.com/watch?v=fBCwfoBr2ng) and a [step-by-step tutorial](https://www.youtube.com/watch?v=nH7qJHx-h5s).

For your answer, affirm that you *either* completed the tutorial or have previous experience with all of the concepts above. Do this by typing your name below and selecting the situation that applies from the two options in brackets.

**ANSWER**

*I, [**Maobin Guo**], affirm that I have [**completed the above tutorial / I have previous experience that covers all the content in this tutorial**]*

# Exploratory Data Analysis
## 13
**[20 points]** Here you'll bring together some of the individual skills that you demonstrated above and create a Jupyter notebook based blog post on data analysis.

1. Find a dataset that interests you and relates to a question or problem that you find intriguing
2. Using a Jupyter notebook, describe the dataset, the source of the data, and the reason the dataset was of interest.
3. Check the data and see if they need to be cleaned: are there missing values? Are there clearly erroneous values? Do two tables need to be merged together? Clean the data so it can be visualized.
3. Plot the data, demonstrating interesting features that you discover. Are there any relationships between variables that were surprising or patterns that emerged? Please exercise creativity and curiosity in your plots.
4. What insights are you able to take away from exploring the data? Is there a reason why analyzing the dataset you chose is particularly interesting or important? Summarize this as if your target audience was the readership of a major news organization - boil down your findings in a way that is accessible, but still accurate.

Here your analysis will evaluated based on:
1. Data cleaning: did you look for and work to resolve issues in the data?
2. Quality of data exploration: did you provide plots demonstrating interesting aspects of the data?
3. Interpretation: Did you clearly explain your insights? Restating the data, alone, is not interpretation.
5. Professionalism: Was this work done in a way that exhibits professionalism through clarity, organization, high quality figures and plots, and meaningful descriptions?

**ANSWER**